import 'package:http/http.dart';

import 'cluster_auth_client.dart';

class BearerClient extends BaseClient implements ClusterAuthClient {
  BearerClient({required this.token, this.expirationTimestamp});

  final String token;
  final DateTime? expirationTimestamp;

  @override
  Future<StreamedResponse> send(BaseRequest request) async {
    throw UnimplementedError('BearerClient is not implemented');
  }

  /// Creates a [BearerClient] instance from a JSON map.
  ///
  /// This factory constructor is generated by json_serializable.
  factory BearerClient.fromJson(Map<String, dynamic> json) =>
      throw UnimplementedError('BearerClient is not implemented');

  /// Converts this [BearerClient] instance to a JSON map.
  ///
  /// This method is generated by json_serializable.
  @override
  Map<String, dynamic> toJson() =>
      throw UnimplementedError('BearerClient is not implemented');
}
