name: kuberneteslib
description: A library that implements the Kubernetes API natively. It is written using the direct specs and currently covers most of the V1 Core, Apps, and Batch resources.
version: 0.3.12
repository: https://github.com/m3talsmith/kuberneteslib

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.2.2
  humanizer: ^3.0.0
  json2yaml: ^3.0.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
  test: ^1.24.0
