name: kuberneteslib
description: A library that implements the Kubernetes API natively. It is written using the direct specs and currently covers most of the V1 Core, Apps, and Batch resources.
version: 0.3.8
repository: https://github.com/m3talsmith/kuberneteslib

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.2.2
  humanizer: ^3.0.0
  json2yaml: ^3.0.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
