name: kubernetes
description: A Kubernetes API library implementation for dart.
version: 1.0.0
repository: https://github.com/m3talsmith/kuberneteslib

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
