import 'package:json_annotation/json_annotation.dart';

part 'status.g.dart';

/// Represents a status object that can be created from a map.
///
/// This class is used to parse and store status information from a Map structure,
/// typically received from an API or database. It provides JSON serialization
/// support through the json_serializable package.
///
/// Example usage:
/// ```dart
/// final statusJson = {'key': 'value'};
/// final status = Status.fromJson(statusJson);
/// final backToJson = status.toJson();
/// ```
@JsonSerializable()
class Status {
  /// Creates a new empty Status instance.
  Status();

  /// Creates a [Status] instance from a JSON map.
  ///
  /// This factory constructor is generated by json_serializable.
  factory Status.fromJson(Map<String, dynamic> json) => _$StatusFromJson(json);

  /// Converts this [Status] instance to a JSON map.
  ///
  /// This method is generated by json_serializable.
  Map<String, dynamic> toJson() => _$StatusToJson(this);
}
